### ISSUE TITLE
Advocate for `repeatOnLifecycle`?

### ISSUE THREAD

**Issue by p-lr** [psteiger/flow-lifecycle-observer#7]
Hi @psteiger,

Jose Alcérreca has posted [an article](https://link.medium.com/Ljbs0g2Ykgb) about Flows and LiveData, and at the end he describes the rationale behind `repeatOnLifecycle`, which is exactly the purpose of what we've done here.

`repeatOnLifecycle` is part of `lifecycle-runtime-ktx 2.4.0-alpha01` (so still alpha for the moment). We could mention that in the readme, but it's your call.

**Comment by psteiger** [comment]
@peterLaurence you are correct.

I will update the README and my medium article to note Google now offers an official solution to this use-case.

Thanks for noticing and reporting!
