### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by hamen** [psteiger/flow-lifecycle-observer#9]
Hi all, and thank you for the awesome lib 💪🏻

Would it be unreasonable to have a LICENSE file that specifies with license the library is distributed with?

We are tidying up the licenses' situation in one of our apps, and we hit a blocker with `flow-lifecycle-observer`.

Thanks a lot 😍

**Comment by psteiger** [comment]
Hi @hamen,

Just added a LICENSE file. Thanks!
